### ISSUE TITLE
 After a PluginUpdate, I get errors:

### ISSUE THREAD

**Issue by enmy211** [hkupty/iron.nvim#167]
###
**Error during processing of function <SNR>47_save_pos:
line 6: 
E117: Unknown function: nvim_buf_set_extmark**

I have:
   NVIM v0.4.4
   Python 3.7.3
   pynvim 0.4.3
   Ubuntu 18.04.5 LTS

Any idea?

**Comment by GCBallesteros** [comment]
Hi, same error here. As soon as I type `ctr` in normal mode, the following error message shows up:
```
Error detected while processing function <SNR>38_save_pos:
line    6:
E118: Too many arguments for function: nvim_buf_set_extmark
```

### System
Iron: commit 746f2...
Nvim: commit b9ceac46... (HEAD as of 24 September 2020)
REPL: ipython
OS: macOS Catalina 10.15.6

### Config
```lua
local iron = require('iron')

iron.core.set_config {
  preferred = {
    python = "ipython"
  }
}
```

Thanks!

**Comment by GCBallesteros** [comment]
I just did a git bisect and found the first commit to introduce errors to be:
`33d80dbf0c964c...`

**Comment by GCBallesteros** [comment]
Hi @enmy211, I have created a pull request that I think should fix your problem. You can also try for now  [GCBallesteros/iron.nvim](https://github.com/GCBallesteros/iron.nvim) while we wait for a more definitive solution.

Cheers!

**Comment by enmy211** [comment]
Now I get error when use "iron-send-motion"
**Error function <SNR>47_save_pos:**
_line 6_
**E117: Unknown funksjon: nvim_buf_set_extmark**

**Comment by GCBallesteros** [comment]
@enmy211 our errors are actually different.... sorry for having hijacked your issue, I should have read more closely. Your issue is that `nvim_buf_set_extmark` doesn't look to be available on nvim 0.4.4. You may want to try a newer [release](https://github.com/neovim/neovim/releases/tag/nightly)?

**Comment by enmy211** [comment]
With NVIM v0.5.0-715-gc5ceefca7,  I get a little bit different error:

**Error while processing function <SNR>47_save_pos:**
_line 6_
**E118: To many parameters to function: nvim_buf_set_extmark**

**Comment by GCBallesteros** [comment]
@enmy211 That was the error I was getting which I fixed on the pull request. While we wait for a fix here, can you give it a shot to using my version of the plugin, `GCBallesteros/iron.nvim`? Depending on how your plugin manager works you will have to delete the old plugin, update and install the new one. Using Plug, that would be:

1. Remove 'hkrupty/iron.nvim' from init.vim
2. Save, source init.vim and :PlugClean
3. Add 'GCBallesteros/iron.nvim', save, source and :PlugInstall

Hope this helps.

**Comment by enmy211** [comment]
Still with NVIM v0.5.0-715-gc5ceefca7:

**Error while processing function 47_ironSendMotion:**
_line 1:_
**E5108: Error executing lua /home/eivind/.vim/bundle/iron.nvim/lua/iron/init.lua:385: line value outside range**

I tried more and it **worked**!!!
The error pop up a couple of times. I tried more and the error haven't popped up since.

Thank you for fixing this. 

I use this plugin almost every day. Until now I have used Jupyter lab, which isn't my first choice. Now I am on track again!!!

I'll buy you some bear!!!

**Comment by hkupty** [comment]
PR Merged now, @enmy211 can you check if master is fixed for you? Kudos to @GCBallesteros for the fix :)

**Comment by enmy211** [comment]
Yes, it works!

But the very first time I send "ironSendMotion" I get error:
**<SNR>43_ironSendMotion:**
_line 1_
**E5108: Error executing lua /home/eivind/.vim/bundle/iron.nvim/lua/iron/init.lua:392: line value outside range**

After that: No errors.

That's ok.

Thank you. I will buy you some beer (not bear). Paypal?

**Comment by GCBallesteros** [comment]
@enmy211 That's no good, something is still wrong there :) Can you give more details on your workflow from starting nvim to hitting the error? Keystroke for keystroke if necessary. It's hard to diagnose without being able to reproduce first.


P.S. If it's not a bear then I'm not interested ;), but @hkupty may be interested in the beer, he is the one that put in the hard work.

**Comment by enmy211** [comment]
I got to my working directory and fire up nvim with xxxx.py. In my init.vim I have:
`map <leader>9 <Plug>(iron-send-motion)<CR>`

I got to the first line and press my leader-key and the mentioned error show up. I press enter to continue, the command execute ok and _IPython 7.5.0_ pops up in a new window. 

While trying this i discovered exactly where the error occur. 

- When I don't have a empty line at the top of text, the error occur.

- If I have a empty line at the top of text, then no error pops up.


I hope this help :-)

**Comment by GCBallesteros** [comment]
I can reproduce it. It looks like the buffer marks are not set correctly when `iron-send-motion` is called when a REPL is not yet instantiated.

@enmy211 May I suggest that in the meantime you start the REPL before doing the first `iron-send-motion`? That's the way I usually do it. Just call `:IronRepl` from normal mode or make yourself a shortcut. e.g. `nmap <leader>8 :IronRepl<CR>`

**Comment by hkupty** [comment]
I'll have a look at that @enmy211, thanks! And thanks once again @GCBallesteros for the work on identifying and debugging iron :slightly_smiling_face: 

As for the beer, I guess I'll allow me one when I can get back to maintaining iron properly.. Sorry for not being able to keep up.
